### ISSUE TITLE
Only lines in Mindmap, no words

### ISSUE THREAD

**Issue by headacke-evil** [RisingOrange/anki-mindmap#2]
Hello RisingOrange,

I have been working with Anki for about two months and came across your very interesting extension. Especially when structuring the index cards, I find your extension for visualisation very promising. Unfortunately, when I create the file, I can only see the lines. Unfortunately, the terms cannot be displayed.

My first question is: what programme do you use to view your mind maps? Is there a special programme? I currently use Windows Explorer or Edge. Unfortunately, the image could not be viewed with Firefox.

Note:
If I use the note view, I cannot create a file. I realise that this option is still experimental.

I hope you can help me.

P. S.: In case of errors I can send you the text (error code) as a text file. I didn't want to inflate the request unnecessarily.

Regards evil headache

Translated with www.DeepL.com/Translator (free version)

**Comment by RisingOrange** [comment]
Hello evil headache,

I am opening the mind map using a regular image viewer program and I am also able to open them using Firefox. Don't know why it does not work for you. If you send me the resulting image file and the error messages I can try to solve the problem.
