### ISSUE TITLE
I really wanna use this cool add-on. Please help me

### ISSUE THREAD

**Issue by sardine27** [RisingOrange/anki-mindmap#5]
clicking mind map nothing appear. can I get any tips?
![Kapture 2021-05-07 at 21 39 14](https://user-images.githubusercontent.com/82318352/117450997-e653f700-af7c-11eb-96a7-9b2aecc8909a.gif)

**Comment by RisingOrange** [comment]
Hello @sardine27,
first please go to Tools -> Addons and click "Check for updates" to make sure you have the newest version of the add-on. Maybe this will be enough to make it work. Was the add-on working for you before and stopped working now or did you not use it yet?

I haven't tested the add-on on Mac yet, but I will do that if the problems persist.

**Comment by sardine27** [comment]
Oh thanks. now i can check update.
I download this add-on today. so i didn't use yet.
Can I ask one more?
i download graphviz from homebrew. and how can i make sure it is on the PATH?
Is there any command for terminal to add to path to all users?
<img width="563" alt="스크린샷 2021-05-07 오후 11 21 37" src="https://user-images.githubusercontent.com/82318352/117463765-fa9ef080-af8a-11eb-9808-a714b6fac4bd.png">

**Comment by RisingOrange** [comment]
Sure. From what I see from your screenshot grapviz is already on the PATH so you don't have to worry about this.
Try updating the add-on, (restart Anki after an update) and then try to create a mind map. Does it work now? Or does maybe an error message show up?

**Comment by sardine27** [comment]
<img width="1056" alt="스크린샷 2021-05-07 오후 11 38 02" src="https://user-images.githubusercontent.com/82318352/117468938-283a6880-af90-11eb-9077-9ac0af7a98be.png">
I think there's problem with path. i just downloaded and do nothing like setting. can i know how to set path?

**Comment by RisingOrange** [comment]
I updated the add-on. Now you can configure it like this:
https://user-images.githubusercontent.com/31575114/117486069-76884100-af69-11eb-8109-cdbea9753633.mp4
