### ISSUE TITLE
[Suggestion] Option to sort branches alphabetically

### ISSUE THREAD

**Issue by kleinerpirat** [RisingOrange/anki-mindmap#6]
Great add-on, works like a charm on Manjaro Linux!

I came here to ask whether you have any influence on the order of the branches. If yes, an option to sort them by their unicode values (alphabetically) like on the sidebar would be a nice feature.

As you can see in this example deck, the numbered leafs appear in random order:

![image](https://user-images.githubusercontent.com/62722460/118771078-5ff3bb00-b882-11eb-98b0-484273c48257.png)

**Comment by RisingOrange** [comment]
Good idea, I made sorted branches the default now (f008aea9276a442cc521525f3337c750ef27b631). The new version is already on AnkiWeb.

**Comment by kleinerpirat** [comment]
Thanks for the quick response, looking good!

![image](https://user-images.githubusercontent.com/62722460/118782982-ea421c00-b88e-11eb-8e96-fef6557b35d9.png)
